### PR TITLE
clean up / bugfixes / proposal for splitting css files

### PR DESCRIPTION
**Pull request by eitzenbe**
rebased on new master
fixed menu bar, dialog pane not being themed
tab-label unit should have px
code formatted css files
added base file so that color css files can be reduced to only .root 
(So you would have to add TWO css files. The base and a color file, but reduces duplicated code dramatically)

### CODE REVIEW

**Comment by eitzenbe** [comment]
oopsie seems like commits are added to the PR "automatically" so i did the split into base css and color css already, works fine on my app, only thing thats not tackled so far are:

- Datefield button not colored
- Selection area turns gray when field looses focus

**Comment by BlueGoliath** [comment]
Besides the 100px -fx-theme-padding, it looks good to me!

Is there a reason it's set to 100? It's not a big deal since it isn't used, I'm just wondering.

**Comment by eitzenbe** [comment]
no special reason, just mergign all base files together, can be omitted, shall I?

**Comment by BlueGoliath** [comment]
Please do. Will pull then.

Thanks!

**Comment by eitzenbe** [comment]
Do you know how to colorize the datepicker button and the selected are of focus lost fields?

**Comment by BlueGoliath** [comment]
Merged!

All of the CSS properties for the controls are referenced in the default [css file](https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/resources/com/sun/javafx/scene/control/skin/modena/modena.css). 

JavaFX uses a lot of custom properties for various controls so you basically have to use that as a reference.

**Pull request merged**
